import React, { useEffect } from 'react'
import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import { CalendarScheduler } from '../../components/CalendarScheduler'
import { mapArrayEventCalendar } from '../../domain/EventCalendar'
import { getAllEventsCalendar } from '../../services/eventCalendarApi'
import { ContainerMain } from '../../styles/Home'
import { useSession } from 'next-auth/react'

interface IHomeProps {
  listAllEventsCalendar: any
}

const Home = ({ listAllEventsCalendar }: IHomeProps) => {
  const [listEventsCalendar, setListEventsCalendar] = useState<any[]>(listAllEventsCalendar)
  // const eventsCalendar = getAllEventsCalendar()
  // console.log('eventsCalendar', eventsCalendar)
  // const a = listEventsCalendar

  // var b:any[]
  // console.log('listEventsCalendar: ', listEventsCalendar)
  // const { data:session} = useSession()
  // a.forEach((event, index) => {
  //   if (session && session.user?.userid != event.user) {
  //     b.push(event)
  //   }
  // })
  // console.log('listEventsCalendar after', b)

  // useEffect(()=>{
  //   // const a = listEventsCalendar;
  //   // console.log('listEventsCalendar: ', listEventsCalendar)
  //   // const { data:session} = useSession();
  //   // a.forEach((event, index) =>{
  //   //   if (session && session.user?.userid != event.user) {
  //   //     listAllEventsCalendar.splice(index, 1)
  //   //   }
  //   // })
  //   setListEventsCalendar(a)
  // },[JSON.stringify(listEventsCalendar)])

  return (
    <>
      <Head>
        <title>DUDELendar Scheduler</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=""></div>
      <ContainerMain>
        <CalendarScheduler eventsCalendar={listEventsCalendar} />
      </ContainerMain>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  const eventsCalendar = await getAllEventsCalendar();
  console.log("log from server", eventsCalendar)
  const listAllEventsCalendar = mapArrayEventCalendar(eventsCalendar)
  console.log("listAllEventsCalendar: ",listAllEventsCalendar)

  return {
    props: {
      listAllEventsCalendar: listAllEventsCalendar ?? [],
    },
  };
};

export default Home
