import React, { useEffect } from 'react'
import type { GetServerSideProps } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import { CalendarScheduler } from '../../components/CalendarScheduler'
import { mapArrayEventCalendar } from '../../domain/EventCalendar'
import { getAllEventsCalendar, getAllEventsCalendarById } from '../../services/eventCalendarApi'
import { ContainerMain } from '../../styles/Home'
import { useSession } from 'next-auth/react'

interface IHomeProps {
  listAllEventsCalendar: any
}

const Home = ({ listAllEventsCalendar }: IHomeProps) => {
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const [listEventsCalendar, setListEventsCalendar] = useState<any[]>(listAllEventsCalendar)
  const { data: session } = useSession()

  useEffect(() => {
    ;(async () => {
      if (!session) return
      const jsonData = {
        userid: session.userid,
      }
      const eventById = await getAllEventsCalendarById(jsonData)
      console.log('eventById', eventById)
      setListEventsCalendar(eventById)
    })()
  }, [session])

  return (
    <>
      <Head>
        <title>DUDELendar Scheduler</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=""></div>
      <ContainerMain>
        <CalendarScheduler eventsCalendar={listEventsCalendar} />
      </ContainerMain>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  // const session = await getSession()
  // console.log('session from server', session != null ? session : 'nothing')
  const eventsCalendar = await getAllEventsCalendar()
  // console.log("log from server", eventsCalendar)
  const listAllEventsCalendar = mapArrayEventCalendar(eventsCalendar)
  // console.log("listAllEventsCalendar: ",listAllEventsCalendar)

  return {
    props: {
      listAllEventsCalendar: listAllEventsCalendar ?? [],
    },
  }
}

export default Home
