name: Backend Unit Tests
on:
  pull_request:
    branches: ["main"]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: go to backend folder
              run: cd dudelendar-backend
            - name: Install dependencies
              run: npm i
            - name: unit test
              run: npm run test
